version: "3"
services:
  mysql:
    build: ./mysql
    ports:
      - "33060:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      #MYSQL_USER: "user"
      #MYSQL_PASSWORD: "password"
      #MYSQL_DATABASE: "clothesdb"
      MYSQL_ROOT_PASSWORD: "root"